//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageHelper.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageHelper.i18n.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot.
        /// </summary>
        internal static string AddVocabHeader {
            get {
                return ResourceManager.GetString("AddVocabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string DeleteDrop {
            get {
                return ResourceManager.GetString("DeleteDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le dossier.
        /// </summary>
        internal static string DeleteFolderMessage {
            get {
                return ResourceManager.GetString("DeleteFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allemand.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle liste.
        /// </summary>
        internal static string HomeCreateFolder {
            get {
                return ResourceManager.GetString("HomeCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        internal static string HomeCreateFolderPopUp {
            get {
                return ResourceManager.GetString("HomeCreateFolderPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string HomeCreateFolderPopUpClose {
            get {
                return ResourceManager.GetString("HomeCreateFolderPopUpClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la liste.
        /// </summary>
        internal static string HomeCreateFolderPopUpPlaceholder {
            get {
                return ResourceManager.GetString("HomeCreateFolderPopUpPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listes.
        /// </summary>
        internal static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprendre.
        /// </summary>
        internal static string LearnPage {
            get {
                return ResourceManager.GetString("LearnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champs ne doit pas être vide....
        /// </summary>
        internal static string NewFolderError {
            get {
                return ResourceManager.GetString("NewFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot.
        /// </summary>
        internal static string NewWordPopUpPlaceHolder {
            get {
                return ResourceManager.GetString("NewWordPopUpPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traduction.
        /// </summary>
        internal static string NewWordTransPopUpPlaceHolder {
            get {
                return ResourceManager.GetString("NewWordTransPopUpPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher une liste....
        /// </summary>
        internal static string SearchFolder {
            get {
                return ResourceManager.GetString("SearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherche une liste de vocabulaire en tapant son nom....
        /// </summary>
        internal static string SearchFolderExplanation {
            get {
                return ResourceManager.GetString("SearchFolderExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer.
        /// </summary>
        internal static string UpdateDrop {
            get {
                return ResourceManager.GetString("UpdateDrop", resourceCulture);
            }
        }
    }
}
